# Generated by Django 4.2.5 on 2023-10-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_eagle", models.CharField(max_length=50)),
                ("create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
