# Generated by Django 4.2.5 on 2023-10-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
    ]
